### ISSUE TITLE
Add standard MIT license

### ISSUE THREAD

**Issue by captainbarbosa** [segiddins/xcinvoke#8]
Hi @segiddins, would it be possible to add a standard MIT license to this repository since [Jazzy](https://github.com/realm/jazzy#license) also has one?

**Comment by Footpad** [comment]
@segiddins Before I can use xcinvoke (Jazzy, really), my work requires that I know the license. Is xcinvoke going to be licensed under MIT or some other license?

**Comment by segiddins** [comment]
I'll have a quick think about this, thanks for the reminder. Don't know how I missed this issue back in June

**Comment by kmacdona** [comment]
@segiddins Can a license please be added?
